#! /bin/bash

g++ -o ~/Programming/Gengine/bin/GRAPHICS_ENGINE.exe ~/Programming/Gengine/src/*/*.cpp ~/Programming/Gengine/include/*/*.h ~/Programming/Gengine/libs/*/*.c  ~/Programming/Gengine/libs/*/*.cpp -ldl -lglfw
