# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.25

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/laelijah/Programming/Gengine

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/laelijah/Programming/Gengine

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/laelijah/Programming/Gengine/CMakeFiles /home/laelijah/Programming/Gengine//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/laelijah/Programming/Gengine/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named Gengine

# Build rule for target.
Gengine: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Gengine
.PHONY : Gengine

# fast build rule for target.
Gengine/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Gengine.dir/build.make CMakeFiles/Gengine.dir/build
.PHONY : Gengine/fast

external/GLAD/glad.o: external/GLAD/glad.c.o
.PHONY : external/GLAD/glad.o

# target to build an object file
external/GLAD/glad.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Gengine.dir/build.make CMakeFiles/Gengine.dir/external/GLAD/glad.c.o
.PHONY : external/GLAD/glad.c.o

external/GLAD/glad.i: external/GLAD/glad.c.i
.PHONY : external/GLAD/glad.i

# target to preprocess a source file
external/GLAD/glad.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Gengine.dir/build.make CMakeFiles/Gengine.dir/external/GLAD/glad.c.i
.PHONY : external/GLAD/glad.c.i

external/GLAD/glad.s: external/GLAD/glad.c.s
.PHONY : external/GLAD/glad.s

# target to generate assembly for a file
external/GLAD/glad.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Gengine.dir/build.make CMakeFiles/Gengine.dir/external/GLAD/glad.c.s
.PHONY : external/GLAD/glad.c.s

external/STB_IMAGE/stb_image.o: external/STB_IMAGE/stb_image.cpp.o
.PHONY : external/STB_IMAGE/stb_image.o

# target to build an object file
external/STB_IMAGE/stb_image.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Gengine.dir/build.make CMakeFiles/Gengine.dir/external/STB_IMAGE/stb_image.cpp.o
.PHONY : external/STB_IMAGE/stb_image.cpp.o

external/STB_IMAGE/stb_image.i: external/STB_IMAGE/stb_image.cpp.i
.PHONY : external/STB_IMAGE/stb_image.i

# target to preprocess a source file
external/STB_IMAGE/stb_image.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Gengine.dir/build.make CMakeFiles/Gengine.dir/external/STB_IMAGE/stb_image.cpp.i
.PHONY : external/STB_IMAGE/stb_image.cpp.i

external/STB_IMAGE/stb_image.s: external/STB_IMAGE/stb_image.cpp.s
.PHONY : external/STB_IMAGE/stb_image.s

# target to generate assembly for a file
external/STB_IMAGE/stb_image.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Gengine.dir/build.make CMakeFiles/Gengine.dir/external/STB_IMAGE/stb_image.cpp.s
.PHONY : external/STB_IMAGE/stb_image.cpp.s

src/Graphics/Camera.o: src/Graphics/Camera.cpp.o
.PHONY : src/Graphics/Camera.o

# target to build an object file
src/Graphics/Camera.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Gengine.dir/build.make CMakeFiles/Gengine.dir/src/Graphics/Camera.cpp.o
.PHONY : src/Graphics/Camera.cpp.o

src/Graphics/Camera.i: src/Graphics/Camera.cpp.i
.PHONY : src/Graphics/Camera.i

# target to preprocess a source file
src/Graphics/Camera.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Gengine.dir/build.make CMakeFiles/Gengine.dir/src/Graphics/Camera.cpp.i
.PHONY : src/Graphics/Camera.cpp.i

src/Graphics/Camera.s: src/Graphics/Camera.cpp.s
.PHONY : src/Graphics/Camera.s

# target to generate assembly for a file
src/Graphics/Camera.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Gengine.dir/build.make CMakeFiles/Gengine.dir/src/Graphics/Camera.cpp.s
.PHONY : src/Graphics/Camera.cpp.s

src/Graphics/GLCanvas.o: src/Graphics/GLCanvas.cpp.o
.PHONY : src/Graphics/GLCanvas.o

# target to build an object file
src/Graphics/GLCanvas.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Gengine.dir/build.make CMakeFiles/Gengine.dir/src/Graphics/GLCanvas.cpp.o
.PHONY : src/Graphics/GLCanvas.cpp.o

src/Graphics/GLCanvas.i: src/Graphics/GLCanvas.cpp.i
.PHONY : src/Graphics/GLCanvas.i

# target to preprocess a source file
src/Graphics/GLCanvas.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Gengine.dir/build.make CMakeFiles/Gengine.dir/src/Graphics/GLCanvas.cpp.i
.PHONY : src/Graphics/GLCanvas.cpp.i

src/Graphics/GLCanvas.s: src/Graphics/GLCanvas.cpp.s
.PHONY : src/Graphics/GLCanvas.s

# target to generate assembly for a file
src/Graphics/GLCanvas.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Gengine.dir/build.make CMakeFiles/Gengine.dir/src/Graphics/GLCanvas.cpp.s
.PHONY : src/Graphics/GLCanvas.cpp.s

src/Graphics/Globals.o: src/Graphics/Globals.cpp.o
.PHONY : src/Graphics/Globals.o

# target to build an object file
src/Graphics/Globals.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Gengine.dir/build.make CMakeFiles/Gengine.dir/src/Graphics/Globals.cpp.o
.PHONY : src/Graphics/Globals.cpp.o

src/Graphics/Globals.i: src/Graphics/Globals.cpp.i
.PHONY : src/Graphics/Globals.i

# target to preprocess a source file
src/Graphics/Globals.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Gengine.dir/build.make CMakeFiles/Gengine.dir/src/Graphics/Globals.cpp.i
.PHONY : src/Graphics/Globals.cpp.i

src/Graphics/Globals.s: src/Graphics/Globals.cpp.s
.PHONY : src/Graphics/Globals.s

# target to generate assembly for a file
src/Graphics/Globals.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Gengine.dir/build.make CMakeFiles/Gengine.dir/src/Graphics/Globals.cpp.s
.PHONY : src/Graphics/Globals.cpp.s

src/Graphics/Shader.o: src/Graphics/Shader.cpp.o
.PHONY : src/Graphics/Shader.o

# target to build an object file
src/Graphics/Shader.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Gengine.dir/build.make CMakeFiles/Gengine.dir/src/Graphics/Shader.cpp.o
.PHONY : src/Graphics/Shader.cpp.o

src/Graphics/Shader.i: src/Graphics/Shader.cpp.i
.PHONY : src/Graphics/Shader.i

# target to preprocess a source file
src/Graphics/Shader.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Gengine.dir/build.make CMakeFiles/Gengine.dir/src/Graphics/Shader.cpp.i
.PHONY : src/Graphics/Shader.cpp.i

src/Graphics/Shader.s: src/Graphics/Shader.cpp.s
.PHONY : src/Graphics/Shader.s

# target to generate assembly for a file
src/Graphics/Shader.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Gengine.dir/build.make CMakeFiles/Gengine.dir/src/Graphics/Shader.cpp.s
.PHONY : src/Graphics/Shader.cpp.s

src/Graphics/index.o: src/Graphics/index.cpp.o
.PHONY : src/Graphics/index.o

# target to build an object file
src/Graphics/index.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Gengine.dir/build.make CMakeFiles/Gengine.dir/src/Graphics/index.cpp.o
.PHONY : src/Graphics/index.cpp.o

src/Graphics/index.i: src/Graphics/index.cpp.i
.PHONY : src/Graphics/index.i

# target to preprocess a source file
src/Graphics/index.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Gengine.dir/build.make CMakeFiles/Gengine.dir/src/Graphics/index.cpp.i
.PHONY : src/Graphics/index.cpp.i

src/Graphics/index.s: src/Graphics/index.cpp.s
.PHONY : src/Graphics/index.s

# target to generate assembly for a file
src/Graphics/index.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Gengine.dir/build.make CMakeFiles/Gengine.dir/src/Graphics/index.cpp.s
.PHONY : src/Graphics/index.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... Gengine"
	@echo "... external/GLAD/glad.o"
	@echo "... external/GLAD/glad.i"
	@echo "... external/GLAD/glad.s"
	@echo "... external/STB_IMAGE/stb_image.o"
	@echo "... external/STB_IMAGE/stb_image.i"
	@echo "... external/STB_IMAGE/stb_image.s"
	@echo "... src/Graphics/Camera.o"
	@echo "... src/Graphics/Camera.i"
	@echo "... src/Graphics/Camera.s"
	@echo "... src/Graphics/GLCanvas.o"
	@echo "... src/Graphics/GLCanvas.i"
	@echo "... src/Graphics/GLCanvas.s"
	@echo "... src/Graphics/Globals.o"
	@echo "... src/Graphics/Globals.i"
	@echo "... src/Graphics/Globals.s"
	@echo "... src/Graphics/Shader.o"
	@echo "... src/Graphics/Shader.i"
	@echo "... src/Graphics/Shader.s"
	@echo "... src/Graphics/index.o"
	@echo "... src/Graphics/index.i"
	@echo "... src/Graphics/index.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

